import { Review, Deal, Category, ComparisonItem } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Smartphones',
    slug: 'smartphones',
    icon: 'Smartphone',
    tagline: 'Melhores celulares custo-benefício',
  },
  {
    id: '2',
    name: 'Laptops',
    slug: 'laptops',
    icon: 'Laptop',
    tagline: 'Produtos para home office',
  },
  {
    id: '3',
    name: 'Áudio',
    slug: 'audio',
    icon: 'Headphones',
    tagline: 'Melhores fones bluetooth',
  },
  {
    id: '4',
    name: 'Casa Inteligente',
    slug: 'casa-inteligente',
    icon: 'Home',
    tagline: 'Itens de casa inteligente',
  },
  {
    id: '5',
    name: 'Acessórios',
    slug: 'acessorios',
    icon: 'Cable',
    tagline: 'Acessórios para iPhone',
  },
  {
    id: '6',
    name: 'Videogames',
    slug: 'videogames',
    icon: 'Gamepad2',
    tagline: 'Consoles de Nova Geração',
  },
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    title: 'iPhone 17 vs 17 Pro Max: Qual comprar?',
    slug: 'iphone-17-vs-pro-max',
    excerpt:
      'A linha iPhone 17 chegou! Comparamos o custo-benefício da versão base com a brutalidade do Pro Max. Qual deles faz mais sentido hoje?',
    image:
      'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=800',
    category: 'Smartphones',
    author: 'Muniz',
    date: 'Hoje',
    rating: 9.8,
    featured: true,
    benefits: [
      'Novo chip com eficiência brutal e máxima velocidade',
      'Câmeras de nível profissional com zoom óptico turbinado',
      'Acabamento premium em Titânio (Pro Max) com bateria gigante',
    ],
    pros: ['Câmera insuperável', 'Bateria duradoura', 'Maior brilho de tela da categoria'],
    cons: ['O preço do Pro Max ainda é para poucos', 'Pequenas mudanças de design em relação à geração anterior'],
    forWhom:
      'Criadores de conteúdo, quem ama fotografia e qualquer usuário que queira o melhor celular do mundo nas mãos.',
    buyLink: 'https://amzn.to/0fd7497e3331edf66954b0ff160b6429',
    buyPrice: 'Ver Preço Atualizado',
  },
  {
    id: '2',
    title: 'Echo Dot 5ª Geração: A Melhor Alexa Barata?',
    slug: 'echo-dot-5-review',
    excerpt: 'Testamos a nova geração do smart speaker mais popular do Brasil.',
    image:
      'https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&q=80&w=800',
    category: 'Casa Inteligente',
    author: 'Muniz',
    date: '02 de Novembro, 2023',
    rating: 8.8,
    featured: true,
    benefits: [
      'Som com graves mais profundos e vocais nítidos',
      'Sensor de temperatura integrado',
      'Respostas mais rápidas do assistente',
    ],
    pros: ['Excelente custo-benefício', 'Integração fácil com rotinas', 'Tamanho compacto'],
    cons: ['Não tem porta P2 (entrada auxiliar)', 'A versão sem relógio perde um pouco do charme'],
    forWhom:
      'Quem está montando a primeira casa inteligente ou quer espalhar assistentes de voz pelos cômodos com o melhor custo-benefício.',
    buyLink: '#',
    buyPrice: 'R$ 299',
  },
];

export const DEALS: Deal[] = [
  {
    id: '1',
    title: 'Echo Dot 5ª Geração',
    slug: 'echo-dot-5',
    price: 'R$ 299,00',
    originalPrice: 'R$ 429,00',
    discount: '30%',
    store: 'Amazon',
    link: 'https://amzn.to/3Oycf9t',
    image: 'https://m.media-amazon.com/images/I/51OiVQzj4HL.jpg',
    urgencyText: 'Estoque acabando! Restam apenas 5 unidades.',
    endsInHours: 12,
    features: ['Áudio superior', 'Alexa integrada', 'Sensor de temperatura'],
    category: 'Casa Inteligente',
    views: 1245,
    isAchadinho: false,
  },
  {
    id: '2',
    title: 'JBL Tune 520BT',
    slug: 'jbl-tune-520bt',
    price: 'R$ 239,00',
    originalPrice: 'R$ 299,00',
    discount: '20%',
    store: 'Amazon',
    link: 'https://amzn.to/48jjLM9',
    image: 'https://m.media-amazon.com/images/I/31PdqoxM1rL.jpg',
    category: 'Áudio',
    views: 890,
    isAchadinho: false,
  },
  {
    id: '3',
    title: 'Bettdow SmartWatch com Alexa',
    slug: 'bettdow-smartwatch',
    price: 'R$ 159,00',
    originalPrice: 'R$ 299,00',
    discount: '46%',
    store: 'Amazon',
    link: 'https://amzn.to/4ctRVzf',
    image: 'https://m.media-amazon.com/images/I/417Stsz0pZL.jpg',
    category: 'Smartphones',
    views: 3420,
    isAchadinho: false,
  },
  {
    id: '4',
    title: 'Carregador Turbo 50W Lagus',
    slug: 'carregador-turbo-50w',
    price: 'R$ 89,90',
    originalPrice: 'R$ 150,00',
    discount: '40%',
    store: 'Amazon',
    link: 'https://amzn.to/4u4nhSH',
    image: 'https://m.media-amazon.com/images/I/31XoPy39IQL.jpg',
    category: 'Acessórios',
    views: 2100,
    isAchadinho: true,
  },
  {
    id: '5',
    title: 'Cabo USB-C 60W Trançado',
    slug: 'cabo-usbc-60w',
    price: 'R$ 35,90',
    originalPrice: 'R$ 70,00',
    discount: '48%',
    store: 'Amazon',
    link: 'https://amzn.to/4cuewf6',
    image: 'https://m.media-amazon.com/images/I/315bZ8SMwQL.jpg',
    category: 'Acessórios',
    views: 1540,
    isAchadinho: true,
  },
  {
    id: '6',
    title: 'Apple iPhone 17 (256 GB)',
    slug: 'iphone-17',
    price: 'Ver na Loja',
    originalPrice: 'R$ 7.799',
    discount: '15%',
    store: 'Amazon',
    link: 'https://amzn.to/42v19oN',
    image: 'https://m.media-amazon.com/images/I/315WfM6Hp3L.jpg',
    category: 'Smartphones',
    views: 5200,
    isAchadinho: false,
  },
  {
    id: '7',
    title: 'Apple iPhone 17 Pro Max (256 GB)',
    slug: 'iphone-17-pro-max',
    price: 'Ver na Loja',
    originalPrice: 'R$ 12.499',
    discount: '12%',
    store: 'Amazon',
    link: 'https://amzn.to/4tyBKXm',
    image: 'https://m.media-amazon.com/images/I/31L7O+9pfcL.jpg',
    category: 'Smartphones',
    views: 8900,
    isAchadinho: false,
  },
  {
    id: '8',
    title: 'PlayStation 5 Slim Digital',
    slug: 'ps5-slim',
    price: 'R$ 3.799',
    originalPrice: 'R$ 4.499',
    discount: '15%',
    store: 'Amazon',
    link: '#',
    image: 'https://m.media-amazon.com/images/I/41D9HhSgTAL._AC_SL1000_.jpg',
    category: 'Videogames',
    views: 4500,
    isAchadinho: false,
  },
  {
    id: '9',
    title: 'Xbox Series X 1TB',
    slug: 'xbox-series-x',
    price: 'R$ 4.299',
    originalPrice: 'R$ 4.999',
    discount: '14%',
    store: 'Amazon',
    link: '#',
    image: 'https://m.media-amazon.com/images/I/51-mYf69LXL._AC_SL1500_.jpg',
    category: 'Videogames',
    views: 3800,
    isAchadinho: false,
  },
  {
    id: '10',
    title: 'Nintendo Switch OLED',
    slug: 'nintendo-switch-oled',
    price: 'R$ 2.199',
    originalPrice: 'R$ 2.699',
    discount: '18%',
    store: 'Amazon',
    link: '#',
    image: 'https://m.media-amazon.com/images/I/61S97vM7uLL._AC_SL1500_.jpg',
    category: 'Videogames',
    views: 5200,
    isAchadinho: false,
  },
];

export const COMPARISONS: ComparisonItem[] = [
  {
    id: '1',
    title: 'Melhor smartwatch barato em 2026: Galaxy Watch vs Amazfit',
    slug: 'melhor-smartwatch-barato-2026',
    excerpt: 'Colocamos os reis do custo-benefício frente a frente.',
    item1Name: 'Galaxy Watch 6',
    item2Name: 'Amazfit GTR 4',
    image1:
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&q=80&w=400',
    image2:
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '2',
    title: 'Alexa ou Google Nest: Qual escolher para sua casa?',
    slug: 'alexa-vs-google-nest',
    excerpt: 'O duelo definitivo das assistentes virtuais em português.',
    item1Name: 'Amazon Echo',
    item2Name: 'Google Nest',
    image1:
      'https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&q=80&w=400',
    image2:
      'https://images.unsplash.com/photo-1568910748155-01ca989ddda6?auto=format&fit=crop&q=80&w=400',
  },
];

export const PRODUCTS_OF_THE_DAY = REVIEWS.slice(0, 2);
export const MOST_CLICKED = REVIEWS;
